# Generated by Django 5.1.1 on 2024-10-18 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='passwordreset',
            old_name='create_when',
            new_name='created_when',
        ),
    ]
