# Generated by Django 5.1.1 on 2024-11-05 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Core', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
